# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('provider', '0001_initial'), ('provider', '0002_offer_starting_date'), ('provider', '0003_auto_20161106_1506'), ('provider', '0004_auto_20161106_1513'), ('provider', '0005_auto_20161106_1514'), ('provider', '0006_auto_20161106_1848'), ('provider', '0007_auto_20161106_1848'), ('provider', '0008_auto_20161110_0015'), ('provider', '0009_auto_20161110_0016'), ('provider', '0010_auto_20161110_0034'), ('provider', '0011_auto_20161110_0055')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('expiration_date', models.DateTimeField()),
                ('location', models.CharField(max_length=250)),
                ('provider', models.CharField(max_length=250)),
                ('starting_date', models.DateTimeField()),
            ],
        ),
    ]
