# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_squashed_0011_auto_20161110_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
