# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='starting_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
