# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20161110_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
