# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_offer_foreign_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': (('can_create_offer', 'Can create an offer'), ('can_edit_offer', 'Can edit an offer'), ('can_delete_offer', 'Can delete an offer'))},
        ),
    ]
