# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 21:00
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def createGroups(apps, schema_editor):
	group, created = Group.objects.get_or_create(name='provider')   
	if created:
		group.permissions.add(Permission.objects.get(name='Can create an offer'))
		group.permissions.add(Permission.objects.get(name='Can edit an offer'))
		group.permissions.add(Permission.objects.get(name='Can delete an offer'))
		
	group, created = Group.objects.get_or_create(name='consumer')  

class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_offer_permissions'),
    ]

    operations = [
		migrations.RunPython(createGroups)
    ]
